# Generated by Django 4.2.28 on 2026-03-01 17:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TriageRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_message', models.TextField()),
                ('triage_score', models.IntegerField(default=0)),
                ('health_stability_score', models.IntegerField(default=100)),
                ('risk_level', models.CharField(choices=[('Stable', 'Stable (Green)'), ('Monitor', 'Monitor (Yellow)'), ('High Risk', 'High Risk (Red)')], default='Stable', max_length=20)),
                ('medical_advice', models.TextField(blank=True)),
                ('detected_symptoms', models.JSONField(blank=True, default=list)),
                ('recommended_action', models.CharField(blank=True, max_length=200)),
                ('llm_provider', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='api.chatsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('medications', models.JSONField(default=list)),
                ('conditions', models.JSONField(default=list)),
                ('interaction_warnings', models.JSONField(default=list)),
                ('optimized_plan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='api.chatsession')),
            ],
            options={
                'verbose_name': 'Medication Record',
            },
        ),
        migrations.CreateModel(
            name='FacialVerificationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stress_score', models.FloatField(null=True)),
                ('pain_score', models.FloatField(null=True)),
                ('confidence', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('triage_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='facial_data', to='api.triagerecord')),
            ],
            options={
                'verbose_name': 'Facial Verification Record',
            },
        ),
        migrations.AddIndex(
            model_name='triagerecord',
            index=models.Index(fields=['risk_level'], name='api_triager_risk_le_787172_idx'),
        ),
        migrations.AddIndex(
            model_name='triagerecord',
            index=models.Index(fields=['triage_score'], name='api_triager_triage__c4357a_idx'),
        ),
        migrations.AddIndex(
            model_name='triagerecord',
            index=models.Index(fields=['created_at'], name='api_triager_created_068b15_idx'),
        ),
    ]
